// Ground Handling Services Data - organized by supplier type
export const GROUND_HANDLING_SERVICES = [
  "Accounting Surcharge",
  "ACU/GPU Technical support",
  "Additional Counter",
  "Additional Man hrs",
  "Additional Man hrs - Loader/utility hand",
  "Additional PAX Bus",
  "ADHOC Hold Cleaning",
  "Air Condition Unit",
  "Air Condition Unit (30 MIN)",
  "Air Condition Unit (Mobile)",
  "Air Condition Unit-B737",
  "Air Start Unit",
  "Air Start Unit-A330",
  "Aircraft Handling",
  "Aircraft Handling - Discounted (3%)",
  "Aircraft Handling - Discounted (5%)",
  "Aircraft Handling (Beyond Service Hr)",
  "Aircraft Handling- A330",
  "Aircraft Handling- A330 (LIFO)",
  "Aircraft Handling- ATR",
  "Aircraft Handling-A330 (Beyond Service Hr)",
  "Aircraft Handling-A330 (Delay) (LIFO)",
  "AMBULIFT",
  "Baggage Cart (left behind bag)",
  "Baggage Claim",
  "Baggage Colln at boarding-gate",
  "Baggage Colln at departure-gate",
  "Baggage Delivery",
  "Baggage ReConciliation Charge",
  "Baggage Segregation (addi. non standard)",
  "Baggage Tag",
  "Baggage Tag and handling",
  "Baggage Tag and handling (Carrier provided tag)",
  "Being B3 Charges",
  "Being B3 Charges-A330",
  "Boarding Fee",
  "Check In Service",
  "Check-in Counter Charges",
  "Check-in Counter Charges staff",
  "Container Dolly",
  "Conveyor Belt",
  "Credit Note",
  "Credit Note/Excess Baggage sales",
  "Credit Note/Execess baggage Ticket",
  "Credit Note/Ref. 950120991 Container Dolly",
  "Credit Note-7000025969",
  "Crew Coordination",
  "Crew Coordination-B737",
  "Crew Trasportation",
  "DCS",
  "Delay Charge",
  "Detention Room Charge",
  "Disbursement Charge",
  "Dispatch of SCM/UCM Message",
  "Escort Deportee",
  "Excess Baggage Ticket",
  "Excess Hand Baggage Collection",
  "FFM/EDI",
  "Flight cancelation (24 to 12 hours b4 STA)",
  "Flight cancelation (6 or less hours b4 STA)",
  "Flight cancelation (8 or less hours b4 STA)",
  "Flight cancelation (96 or 12 hours b4 STA)",
  "Flight Manifest (customs)",
  "Ground Power Unit",
  "Ground Power Unit-90 KV",
  "Handling charges beyond 2 hr diverted",
  "Headset",
  "Inadmissable Passenger Handling",
  "Ip Room Charges",
  "Ip Room Charges (above 12H)",
  "Landing Charge- B737",
  "Late Arrival Charges (above 60 mins)",
  "Late Arrival Charges (above 120 mins)",
  "Late Arrival Charges (above 180 mins)",
  "Late Arrival Charges-A330 (above 60 mins)",
  "Late Arrival Charges-A330 (above 120 mins)",
  "Lavatory truck per svc",
  "Left Behind Baggage",
  "LMC baggage offload",
  "Lost Baggage",
  "Lounge",
  "Lounge Delay",
  "Lower Deck Loader",
  "MAAS (Meet & assist)",
  "MAAS (Meet & assist) with cart",
  "MAAS (Meet & assist)-CIP",
  "MAT FOLDER DELIVERY",
  "Meals",
  "Meals for Inadmissable PAX",
  "Miscellaneous Cost (Polyethene)",
  "Miscellaneous Cost {Food Coupon}",
  "Navigation Charge",
  "Offload Cargo",
  "Offloading- no show pax",
  "Operational Flight plan (Up to 50pg)",
  "Passenger And Crew Transportation",
  "Passenger Security Service Charge",
  "Passenger Steps",
  "Passenger Transportation",
  "PLRD Regulatory Fee",
  "Portable water",
  "Printing Extra Flight DOC",
  "Printing Flight Plan",
  "PSPT Service Charge",
  "Pushback",
  "Ramp to flight deck communication",
  "Royalty Levy",
  "Screening of General Cargo",
  "Security Charges:",
  "Security Coordination",
  "Supervision Charge (Avia Maldives)",
  "Surcharge on Ground handling",
  "Surcharge on Ground handling-A330",
  "Tav Fee for Bus",
  "Technical Handling",
  "Telex Message",
  "Towing",
  "Transfer of hold bag screening",
  "ULD storage",
  "Unskilled Labour",
  "Use of handling company world tracer 2 letter code",
  "Van-catering",
  "VGDS",
  "Water service",
  "Wheel Chair",
  "Wheel Chair (Arrival- 330, Departure- 400)",
  "Wheel Chair - C",
  "Wheel Chair Additional Charge",
  "Windsheild Cleaning",
];

export const AIRPORT_AUTHORITY_SERVICES = [
  "ABC Transfer",
  "ADVANCED PASSENGER INFORMATION",
  "Aerobridge",
  "Aerobridge additional per 30 min",
  "Aerobridge-A330",
  "Air Condition Unit",
  "Air Development Fee (ADF)",
  "Aircraft Handling",
  "Aircraft Handling- A330",
  "Aircraft Release Service",
  "Airport Building Charge (ABC)",
  "APIS",
  "APPS Arrival",
  "APPS Departure",
  "Check-in Counter Charges",
  "Container Dolly",
  "Credit Note/ Excess Baggage Sales",
  "Credit Note/Excess passenger charge",
  "Credit Note/Infrustructure over charged",
  "Credit Note/passenger fees over charged",
  "DCS",
  "Detention Room Charge",
  "Excess Hand Baggage Collection",
  "Ground Power Unit",
  "INADMISSABLE PASSENGERS FINES",
  "Infrastructure Free",
  "Landing Charge- A330",
  "Landing Charge- ATR",
  "Landing Charge- B737",
  "Line Maintenance Service",
  "luggage check-in",
  "Meals",
  "Navigation Charge",
  "Night-Landing Charges",
  "Parking Charges",
  "Parking Charges: A330",
  "Passenger Facility Charge",
  "Passenger Fee- International",
  "Passenger Security Service Charge",
  "Passenger Service Charge",
  "Power & Air Condition Supply",
  "Power & Air Condition Supply (Additional 15 mins)",
  "PSPT Service Charge",
  "Remote stand",
  "Scientific Research Subsidyfee",
  "Screening of General Cargo",
  "Security Charges",
  "Security Charges: A330",
  "Security Charges: ATR",
  "Security Pass",
  "Shared Space for T3",
  "System",
  "Terminal Facilities Utilization",
  "VGDS",
  "X-REY CHARGES",
];

// Combined services by supplier type
export const SERVICES_BY_SUPPLIER_TYPE: Record<string, string[]> = {
  'Ground Handling': GROUND_HANDLING_SERVICES.sort(),
  'Airport Authority': AIRPORT_AUTHORITY_SERVICES.sort(),
  'Cargo': GROUND_HANDLING_SERVICES.filter(s => s.toLowerCase().includes('cargo') || s.toLowerCase().includes('baggage')).sort(),
  'OverFly': ['Navigation Charge', 'OverFly Fee', 'Transit Fee', 'Airspace Usage Fee'].sort(),
};

export const SUPPLIER_TYPES = ['Airport Authority', 'Ground Handling', 'Cargo', 'OverFly'];

export const STATION_TYPES = ['Domestic', 'International', 'Hub', 'Cargo'];

export const UNITS_OF_MEASUREMENT = [
  'Per Landing',
  'Per Hour',
  'Per Passenger',
  'Per Flight',
  'Per Man Hour',
  'Per Unit',
  'Per Kg',
  'Per Service',
  'Flat Rate',
  'Per Day',
  'Per Movement',
];

export const COUNTRIES = [
  'Afghanistan', 'Albania', 'Algeria', 'Andorra', 'Angola', 'Argentina', 'Armenia', 'Australia',
  'Austria', 'Azerbaijan', 'Bahrain', 'Bangladesh', 'Belarus', 'Belgium', 'Bhutan', 'Bolivia',
  'Bosnia and Herzegovina', 'Botswana', 'Brazil', 'Brunei', 'Bulgaria', 'Cambodia', 'Cameroon',
  'Canada', 'Chile', 'China', 'Colombia', 'Costa Rica', 'Croatia', 'Cuba', 'Cyprus', 'Czech Republic',
  'Denmark', 'Dominican Republic', 'Ecuador', 'Egypt', 'El Salvador', 'Estonia', 'Ethiopia',
  'Finland', 'France', 'Georgia', 'Germany', 'Ghana', 'Greece', 'Guatemala', 'Honduras',
  'Hong Kong', 'Hungary', 'Iceland', 'India', 'Indonesia', 'Iran', 'Iraq', 'Ireland', 'Israel',
  'Italy', 'Jamaica', 'Japan', 'Jordan', 'Kazakhstan', 'Kenya', 'Kuwait', 'Kyrgyzstan', 'Laos',
  'Latvia', 'Lebanon', 'Libya', 'Lithuania', 'Luxembourg', 'Macau', 'Malaysia', 'Maldives',
  'Malta', 'Mexico', 'Moldova', 'Monaco', 'Mongolia', 'Montenegro', 'Morocco', 'Myanmar',
  'Nepal', 'Netherlands', 'New Zealand', 'Nigeria', 'North Korea', 'Norway', 'Oman', 'Pakistan',
  'Panama', 'Paraguay', 'Peru', 'Philippines', 'Poland', 'Portugal', 'Qatar', 'Romania', 'Russia',
  'Saudi Arabia', 'Serbia', 'Singapore', 'Slovakia', 'Slovenia', 'South Africa', 'South Korea',
  'Spain', 'Sri Lanka', 'Sudan', 'Sweden', 'Switzerland', 'Syria', 'Taiwan', 'Tajikistan',
  'Tanzania', 'Thailand', 'Tunisia', 'Turkey', 'Turkmenistan', 'UAE', 'Uganda', 'Ukraine',
  'United Arab Emirates', 'United Kingdom', 'United States', 'Uruguay', 'Uzbekistan', 'Venezuela',
  'Vietnam', 'Yemen', 'Zambia', 'Zimbabwe'
].sort();

export const REGIONS = ['Africa', 'Asia', 'Europe', 'Middle East', 'North America', 'Oceania', 'South America'];

export const CURRENCIES = ['USD', 'EUR', 'GBP', 'BDT', 'INR', 'SGD', 'AED', 'SAR', 'MYR', 'THB', 'CNY', 'JPY', 'AUD'];

export interface Station {
  id: string;
  type: 'Domestic' | 'International' | 'Hub' | 'Cargo';
  iataCode: string;
  icaoCode: string;
  name: string;
  country: string;
  region: string;
  status: 'Active' | 'Inactive';
}

// Mock data for stations
export const mockStations: Station[] = [
  { id: '1', type: 'International', iataCode: 'DAC', icaoCode: 'VGZR', name: 'Hazrat Shahjalal International Airport', country: 'Bangladesh', region: 'Asia', status: 'Active' },
  { id: '2', type: 'International', iataCode: 'DXB', icaoCode: 'OMDB', name: 'Dubai International Airport', country: 'United Arab Emirates', region: 'Middle East', status: 'Active' },
  { id: '3', type: 'International', iataCode: 'SIN', icaoCode: 'WSSS', name: 'Singapore Changi Airport', country: 'Singapore', region: 'Asia', status: 'Active' },
  { id: '4', type: 'Domestic', iataCode: 'CGP', icaoCode: 'VGEG', name: 'Shah Amanat International Airport', country: 'Bangladesh', region: 'Asia', status: 'Active' },
  { id: '5', type: 'International', iataCode: 'CCU', icaoCode: 'VECC', name: 'Netaji Subhas Chandra Bose International Airport', country: 'India', region: 'Asia', status: 'Active' },
  { id: '6', type: 'Hub', iataCode: 'BKK', icaoCode: 'VTBS', name: 'Suvarnabhumi Airport', country: 'Thailand', region: 'Asia', status: 'Active' },
  { id: '7', type: 'Cargo', iataCode: 'HKG', icaoCode: 'VHHH', name: 'Hong Kong International Airport', country: 'China', region: 'Asia', status: 'Active' },
];

// Mock data for suppliers
export const mockSuppliers = [
  { id: '1', name: 'Dubai Airports Corporation', type: 'Airport Authority', country: 'United Arab Emirates', station: 'DXB', contactName: 'Ahmed Al Maktoum', status: 'Active', agreementEnd: '2027-06-30' },
  { id: '2', name: 'Swissport International', type: 'Ground Handling', country: 'Singapore', station: 'SIN', contactName: 'Hans Mueller', status: 'Expiring Soon', agreementEnd: '2026-05-15' },
  { id: '3', name: 'Eurocontrol', type: 'OverFly', country: 'Bangladesh', station: 'DAC', contactName: 'Marie Dubois', status: 'Expired', agreementEnd: '2025-12-31' },
  { id: '4', name: 'Singapore Changi Airport', type: 'Airport Authority', country: 'Singapore', station: 'SIN', contactName: 'Lee Wei Ming', status: 'Active', agreementEnd: '2028-01-01' },
  { id: '5', name: 'Menzies Aviation', type: 'Ground Handling', country: 'India', station: 'CCU', contactName: 'James Wilson', status: 'Expired', agreementEnd: '2025-08-30' },
];

// Mock data for services
export const mockServices = [
  { id: '1', code: 'LND-001', name: 'Runway Landing Fee', supplierTypes: ['Airport Authority'], units: ['Per Landing'], criteria: ['Weight-based', 'Aircraft type'] },
  { id: '2', code: 'PKG-001', name: 'Aircraft Parking', supplierTypes: ['Airport Authority', 'Ground Handling'], units: ['Per Hour'], criteria: ['Duration'] },
  { id: '3', code: 'PAX-001', name: 'Passenger Handling', supplierTypes: ['Ground Handling'], units: ['Per Passenger'], criteria: ['Passenger count'] },
  { id: '4', code: 'FUL-001', name: 'Fuel Handling', supplierTypes: ['Ground Handling'], units: ['Per Flight'], criteria: [] },
  { id: '5', code: 'WCH-001', name: 'Wheel Chair', supplierTypes: ['Ground Handling', 'Airport Authority'], units: ['Per Hour', 'Per Man Hour'], criteria: ['Distance', 'Duration'] },
];

// Mock journey log data
export const mockJourneyLogs = [
  { id: '1', flightNo: 'BS-101', flightDate: '05 Feb 2026', aircraftReg: 'S2-AHV', aircraftType: 'B737-800', station: 'DAC', aircraftWeight: '78000', arrivalTime: '08:30', departureTime: '10:15', flightStatus: 'Arrived', serviceEntryStatus: 'Not Started' },
  { id: '2', flightNo: 'BS-102', flightDate: '05 Feb 2026', aircraftReg: 'S2-AHW', aircraftType: 'A330', station: 'DXB', aircraftWeight: '120000', arrivalTime: '09:45', departureTime: '12:00', flightStatus: 'Arrived', serviceEntryStatus: 'Draft' },
  { id: '3', flightNo: 'BS-103', flightDate: '05 Feb 2026', aircraftReg: 'S2-AHX', aircraftType: 'B737-800', station: 'SIN', aircraftWeight: '78000', arrivalTime: '11:00', departureTime: '13:30', flightStatus: 'Delayed', serviceEntryStatus: 'Submitted' },
  { id: '4', flightNo: 'BS-104', flightDate: '05 Feb 2026', aircraftReg: 'S2-AHY', aircraftType: 'ATR', station: 'CGP', aircraftWeight: '23000', arrivalTime: '14:15', departureTime: '16:00', flightStatus: 'Arrived', serviceEntryStatus: 'Approved' },
  { id: '5', flightNo: 'BS-105', flightDate: '05 Feb 2026', aircraftReg: 'S2-AHZ', aircraftType: 'A330', station: 'CCU', aircraftWeight: '120000', arrivalTime: '16:30', departureTime: '18:45', flightStatus: 'Cancelled', serviceEntryStatus: 'Not Started' },
];

// Mock invoices
export const mockInvoices = [
  { id: '1', invoiceNo: 'INV-2026-001', supplier: 'Dubai Airports Corporation', station: 'DXB', amount: 15000, currency: 'AED', invoiceDate: '2026-01-15', dueDate: '2026-02-15', status: 'Pending' },
  { id: '2', invoiceNo: 'INV-2026-002', supplier: 'Swissport International', station: 'SIN', amount: 8500, currency: 'SGD', invoiceDate: '2026-01-20', dueDate: '2026-02-10', status: 'Due Soon' },
  { id: '3', invoiceNo: 'INV-2026-003', supplier: 'Singapore Changi Airport', station: 'SIN', amount: 12000, currency: 'SGD', invoiceDate: '2026-01-10', dueDate: '2026-02-05', status: 'Overdue' },
  { id: '4', invoiceNo: 'INV-2026-004', supplier: 'Menzies Aviation', station: 'CCU', amount: 5000, currency: 'INR', invoiceDate: '2026-01-25', dueDate: '2026-02-25', status: 'Paid' },
];
